### ISSUE TITLE
Add documentation on public methods/functions

### ISSUE THREAD

**Issue by AngeloStavrow** [writefreely/writefreely-swift#2]
The public methods/functions in `WriteFreelyClient` already leverage Xcode documentation comments, so using the package in Xcode gives you nice inline help. However, it's helpful to have documentation accessible outside of the IDE as text.

It's preferred that such documentation be agnostic to whatever code-sharing platform the source is hosted on; in other words, prefer something like Markdown files in a `/docs` folder over using a feature like GitHub Wikis.

It isn't a bad idea to make it such that we can, for example, publish the files in the `/docs` to a GitHub Pages site.

**Comment by AngeloStavrow** [comment]
Okay, so, using [SwiftDoc](https://github.com/SwiftDocOrg/swift-doc) gives us two formatting options:

- **HTML**, which is hard to read in a text editor (and is relative to some typically-unhelpful base URL) but looks great as a static website.
- **Markdown**, which is much easier to read in a text editor, but includes some cruft meant for deploying to a GitHub wiki (but is easily ignored).

You can see what the Markdown output looks like here: https://github.com/writeas/writefreely-swift/tree/add_documentation/docs

In that directory, `Home.md`, `_Footer.md`, and `_Sidebar.md` are all pretty much useless, but we _could_ use [this GitHub action](https://github.com/SwiftDocOrg/github-wiki-publish-action) to push it into the wiki for this repository.

That becomes a GitHub-specific thing, yes, but it's running _on GitHub_ with no effect if the source code is moved to another remote code-hosting service, except for the extra cruft files mentioned above (and some GitHub Actions YAML file). It would otherwise be relatively straightforward to set up something that removes/renames these files as part of #6, I think.

@thebaer Any thoughts/preferences?

**Comment by thebaer** [comment]
I'm definitely more for open solutions here instead of ones tied to GH, though I'm also not exceptionally opposed to GH if it's much more expedient and not super lockin-ey.

Markdown is probably better for the sake of portability -- it could even allow things like publishing docs with WF in the future. And it's probably easier for combining those separate parts if we ever need to do that.

**Comment by AngeloStavrow** [comment]
Sounds good, and I'll add a clean-up task to #6 for removing the extraneous files. 👍

**Comment by AngeloStavrow** [comment]
Closed by #12.
